; Generated by `piton grammar`.
;
; The grammar is line-oriented, so the only structural fold it can offer is a
; wrapped import list. Block folding comes from `piton lsp`, which uses the
; compiler's own indentation-aware tree.
(import_list) @fold
(code_block) @fold
