; Generated by `piton grammar`.
;
; Specific patterns come first: prose is captured only inside a value, so a
; name never falls through to the catch-all.

(comment) @comment

[
  "anchor"
  "abstract"
  "extends"
  "as"
  "export"
  "from"
  "import"
  "use"
] @keyword

(anchor_declaration name: (word) @type.definition)
(keyword_declaration keyword: (word) @keyword.function)
(keyword_declaration name: (word) @type.definition)
(extends_clause name: (word) @type)
(as_clause keyword: (word) @keyword.function)

(import_item name: (word) @variable)
(import_item alias: (word) @variable)
(export_statement name: (word) @variable)
(path) @string.special.path
(import_statement "*" @punctuation.special)

(key) @property
(typed_key) @property
(builtin_type) @type.builtin
(type name: (word) @type)

; The sigil token carries its own `{`, because the lexer needs it to beat the
; word it would otherwise be. The closing brace has to be given the same scope
; explicitly, or an interpolation is bright at one end and dim at the other.
(sigil) @keyword.operator
(interpolation "}" @keyword.operator)
(expression (identifier) @variable)
(self_reference) @variable.builtin
(constant) @constant.builtin
(number) @number
(string) @string
(url) @string.special.url
(escape) @string.escape
(operator) @operator

(list_item "-" @punctuation.special)
(spread_item ["+" "++"] @operator)

[":" "::" ","] @punctuation.delimiter
["[" "]" "(" ")"] @punctuation.bracket

; Prose, last so that nothing more specific is overwritten.
(value (word) @string)
(element (word) @string)

; Keywords contributed by registered frameworks.
((keyword_declaration keyword: (word) @keyword.function)
  (#match? @keyword.function "^(agent|belay-adapter|belay-agent-adapter|belay-config|command|instruction|skill)$"))
