; Generated by `piton grammar`.
;
; A line ending in `:` opens a block; editors that prefer regex indent rules
; find the same thing in the language configuration.
((property) @indent
  (#match? @indent ":$"))

((anchor_declaration) @indent)
((keyword_declaration) @indent)
