; Generated by `piton grammar`.
(anchor_declaration
  ["export" "abstract" "anchor"]* @context
  name: (word) @name) @item

(keyword_declaration
  keyword: (word) @context
  name: (word) @name) @item

(property key: (key) @name) @item
(property key: (typed_key) @name) @item
